ERROR::2022-09-05 00:21:38,049::Internal Server Error: /caterory/1/::/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/utils/log.py::(<class 'AttributeError'>, AttributeError("'Page' object has no attribute 'page'"), <traceback object at 0x7f16a2513240>)
Traceback (most recent call last):
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/sergey/SkillFactory/NewsPortal/NewsPaper/news/views.py", line 94, in get_context_data
    ic(context.get('page_obj').page)
AttributeError: 'Page' object has no attribute 'page'
ERROR::2022-09-05 00:21:38,311::"GET /caterory/1/ HTTP/1.1" 500 110138::/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py::None
ERROR::2022-09-05 00:21:55,394::Internal Server Error: /::/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/utils/log.py::(<class 'AttributeError'>, AttributeError("'Page' object has no attribute 'page'"), <traceback object at 0x7f16a2dbecc0>)
Traceback (most recent call last):
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/sergey/SkillFactory/NewsPortal/NewsPaper/news/views.py", line 48, in get_context_data
    ic(context.get('page_obj').page)
AttributeError: 'Page' object has no attribute 'page'
ERROR::2022-09-05 00:21:55,521::"GET / HTTP/1.1" 500 111166::/home/sergey/SkillFactory/NewsPortal/venv/lib/python3.9/site-packages/django/core/servers/basehttp.py::None
